language: java

env:
 global:
    - PROTOBUF_VERSION=2.5.0

before_install:
  - chmod +x ./install-protobuf.sh
  - ./install-protobuf.sh

after_success:
  - mvn clean test jacoco:report coveralls:report