language: java

jdk:
    - oraclejdk8

env:
 global:
    - PROTOBUF_VERSION=2.5.0

before_install:
  - chmod +x ./install-protobuf.sh
  - ./install-protobuf.sh

script: mvn -B clean test

after_success:
  - mvn -e clean test jacoco:report coveralls:report