language: java

jdk:
    - oraclejdk8

sudo: false

cache:
  directories:
  - $HOME/protobuf

env:
 global:
    - PROTOBUF_VERSION=2.5.0

before_install:
  - chmod +x ./install-protobuf.sh
  - ./install-protobuf.sh
  - export PATH=$PATH:${HOME}/protobuf/bin

install: true

script: mvn -B clean test jacoco:report coveralls:report
