language: java

jdk:
    - oraclejdk8

sudo: false

cache:
  directories:
  - $HOME/protobuf

env:
 global:
    - PROTOBUF_VERSION=2.5.0

before_install:
  - chmod +x ./install-protobuf.sh
  - ./install-protobuf.sh
  - export PATH=$PATH:${HOME}/protobuf/bin
  - echo "MAVEN_OPTS='-Xmx2g -XX:MaxPermSize=512m'" > ~/.mavenrc

install : true

script: mvn -B clean test jacoco:report coveralls:report
